[package]
name = "small_example_pthread"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.0", features = ["bundled"] }
# rusqlite = { git = "https://github.com/oligamiq/rusqlite", features = ["bundled"] }
